-- AlterTable
ALTER TABLE "BeneficiaryRequest" ADD COLUMN "shBecameDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "BeneficiaryRequest" ADD COLUMN "ownerBecameDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
